
DROP TABLE MEMBER
CASCADE CONSTRAINTS;

DROP SEQUENCE MEMBER_SEQ;

CREATE TABLE MEMBER(
	MEMBER_SEQ NUMBER(8) NOT NULL,
	EMAIL VARCHAR2(100) PRIMARY KEY,
	PASSWORD VARCHAR2(100) NOT NULL,
	ADDRESS VARCHAR2(500),
	PHONENUMBER VARCHAR2(50) NOT NULL,
	USERNAME VARCHAR2(50),
	MEMBER_DATE VARCHAR2(50) NOT NULL,
	AUTH NUMBER(2) NOT NULL	/*회원:0,관리자3 */
);

CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1;

UPDATE MEMBER
SET PASSWORD='admin'
WHERE EMAIL='admin'

INSERT INTO MEMBER
VALUES(MEMBER_SEQ.NEXTVAL, 'admin', 'admin', '', '010-0000-0000', '관리자', SYSDATE, 3)

SELECT * FROM BBS

CREATE TABLE MEMBER2(
	ID VARCHAR2(100) PRIMARY KEY,
	PWD VARCHAR2(100) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(200) NOT NULL,
	AUTH NUMBER(3) NOT NULL
);


DROP TABLE PDS
CASCADE CONSTRAINTS;

DROP SEQUENCE PDS_BBS;

CREATE TABLE BBS(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	
	REF NUMBER(8) NOT NULL,
	STEP NUMBER(8) NOT NULL,
	DEPTH NUMBER(8) NOT NULL,
	
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WDATE DATE NOT NULL,
	PARENT NUMBER(8) NOT NULL,
	
	DEL NUMBER(1) NOT NULL,
	READCOUNT NUMBER(8) NOT NULL
);

CREATE SEQUENCE SEQ_BBS
START WITH 1
INCREMENT BY 1;

INSERT INTO BBS (SEQ, ID, REF, STEP, DEPTH, TITLE, CONTENT, WDATE, PARENT, DEL, READCOUNT)
VALUES (SEQ_BBS.NEXTVAL, 'loveelf1',(SELECT NVL(MAX(REF), 0)+1 FROM BBS), 0, 0, '제목', '내용', SYSDATE, 0, 0, 0)



ALTER TABLE BBS
ADD CONSTRAINT FK_BBS_ID FOREIGN KEY(ID)
REFERENCES MEMBER2(ID);



DROP TABLE PDS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_PDS;

CREATE TABLE PDS(
	SEQ NUMBER(8) PRIMARY KEY,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	OLDFILENAME VARCHAR2(50) NOT NULL,
	FILENAME VARCHAR2(50) NOT NULL,
	READCOUNT NUMBER(8) NOT NULL,
	DOWNCOUNT NUMBER(8) NOT NULL,
	REGDATE DATE NOT NULL
);

CREATE SEQUENCE SEQ_PDS
START WITH 1
INCREMENT BY 1;

ALTER TABLE PDS
ADD CONSTRAINT FK_PDS_ID FOREIGN KEY(ID)
REFERENCES MEMBER2(ID);


DROP TABLE POLL
CASCADE CONSTRAINTS;

DROP SEQUENCE POLL_SEQ;

CREATE TABLE POLL(
	POLLID NUMBER NOT NULL,
	ID VARCHAR2(50) NOT NULL,
	QUESTION VARCHAR2(50) NOT NULL,
	SDATE DATE NOT NULL,
	EDATE DATE NOT NULL,
	ITEMCOUNT NUMBER NOT NULL,
	POLLTOTAL NUMBER NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT POLL_PK PRIMARY KEY(POLLID)
);

CREATE SEQUENCE POLL_SEQ
START WITH 1
INCREMENT BY 1;

ALTER TABLE POLL ADD CONSTRAINT POLL_FK
FOREIGN KEY(ID)
REFERENCES MEMBER2(ID);