/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2020-03-19 12:50:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import dto.OrderListDto;
import java.util.List;
import dto.MemberDto;

public final class Store_005fOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("dto.MemberDto");
    _jspx_imports_classes.add("dto.OrderListDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/TAMINO/Store/css/Store_List.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/TAMINO/Store/css/MyPageOverlay.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR|Roboto|Roboto+Mono|Viga&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("width:100%; \r\n");
      out.write("\r\n");
      out.write("background-size: 100%;\r\n");
      out.write("background-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box1{\r\n");
      out.write("width: 60%;\r\n");
      out.write("height:auto;\r\n");
      out.write("margin: 0 auto;\r\n");
      out.write("margin-top: 130px;\r\n");
      out.write("margin-bottom: 100px;\r\n");
      out.write("padding-bottom: 200px;\r\n");
      out.write("/* border: solid 1px;\r\n");
      out.write("border-color: red; */\r\n");
      out.write("}\r\n");
      out.write(".table1 {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("    border-top: 1px solid #6C6C6C;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write(".table2{\r\n");
      out.write("\twidth: 50%;\r\n");
      out.write("    border-top: 1px solid #6C6C6C;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("  th, td {\r\n");
      out.write("    border-bottom: 1px solid #6C6C6C;\r\n");
      out.write("     padding: 10px; \r\n");
      out.write("}\r\n");
      out.write(".lines{\r\n");
      out.write("border-right: 1px solid #B4B4B4;\r\n");
      out.write("} \r\n");
      out.write(".title{\r\n");
      out.write("background-color: #EAEAEA;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write(".btn2{\r\n");
      out.write("border: none;\r\n");
      out.write("margin-top:15px;\r\n");
      out.write("width:300px;\r\n");
      out.write("height:50px;\r\n");
      out.write("font-size:1.5em;\r\n");
      out.write("background-color: black;\r\n");
      out.write("color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#newbtn{\r\n");
      out.write("border: none;\r\n");
      out.write("width:120px;\r\n");
      out.write("height:30px;\r\n");
      out.write("font-size:1em;\r\n");
      out.write("background-color: black;\r\n");
      out.write("color: white;\r\n");
      out.write("margin-bottom: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".adbtn{\r\n");
      out.write("border: none;\r\n");
      out.write("width:120px;\r\n");
      out.write("height:30px;\r\n");
      out.write("font-size:1em;\r\n");
      out.write("background-color: black;\r\n");
      out.write("color: white;\r\n");
      out.write("line-height: 2px;\r\n");
      out.write("}\r\n");
      out.write("#phone{\r\n");
      out.write("width:200px;\r\n");
      out.write("height:30px;\r\n");
      out.write("color:black;\r\n");
      out.write("margin:auto;\r\n");
      out.write("font-size:1em;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("width:200px;\r\n");
      out.write("height:30px;\r\n");
      out.write("color:black;\r\n");
      out.write("margin:auto;\r\n");
      out.write("font-size:1em;\r\n");
      out.write("outline: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#request{\r\n");
      out.write("width:600px;\r\n");
      out.write("height:35px;\r\n");
      out.write("font-size:1em;\r\n");
      out.write("}\r\n");
      out.write("#mbox{\r\n");
      out.write("    border-bottom: 1px solid #6C6C6C;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    text-align: right;\r\n");
      out.write("}\r\n");
      out.write(" \r\n");
      out.write("#memo{\r\n");
      out.write("width:400px;\r\n");
      out.write("height:30px;\r\n");
      out.write("}\t\r\n");
      out.write(".cardimg{\r\n");
      out.write("width:30px;\r\n");
      out.write("height:20px;\r\n");
      out.write("}\r\n");
      out.write("#cardinput{\r\n");
      out.write("text-align: left;\r\n");
      out.write("border: solid 1px;\r\n");
      out.write("margin-left: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cardbig{\r\n");
      out.write("margin-top:50px;\r\n");
      out.write("width:400px;\r\n");
      out.write("height:230px;\r\n");
      out.write("}\r\n");
      out.write("#selboxDirect{\r\n");
      out.write("width: 600px\r\n");
      out.write("}\r\n");
      out.write("#pline{\r\n");
      out.write("    border-left: 1px solid #6C6C6C;\r\n");
      out.write("}\r\n");
      out.write(".box5{\r\n");
      out.write("float:left;\r\n");
      out.write("width: 550px;\r\n");
      out.write("height: 400px;\r\n");
      out.write("margin-left: 3rem;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write(".box5#box6{\r\n");
      out.write("float:left;\r\n");
      out.write("width: 400px;\r\n");
      out.write("height: 400px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".address#sample2_address{\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tline-height: 2px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".steptext{\r\n");
      out.write("\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\tfont-size: 11pt;\r\n");
      out.write("}\r\n");
      out.write(".btn2{\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn2#btn3:hover{\r\n");
      out.write("\tbackground-color: indianred;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn2#btn4:hover{\r\n");
      out.write("\tbackground-color: #008c9e;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("</style>\r\n");

//로그인 정보 얻어오기
Object ologin = session.getAttribute("login");
MemberDto mem = null;
mem = (MemberDto)ologin;


      out.write('\r');
      out.write('\n');

	String currId = "guest";
	if( request.getSession().getAttribute("login") != null ){
		MemberDto loginDto = (MemberDto)request.getSession().getAttribute("login");
		currId = loginDto.getEmail();
	}

      out.write("\r\n");
      out.write("<!-- 네비게이션바 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--주소  -->\r\n");
      out.write("\r\n");
      out.write("<div id=\"layer\" style=\"display:none;position:fixed;overflow:hidden;z-index:1;-webkit-overflow-scrolling:touch;\">\r\n");
      out.write("<img src=\"//t1.daumcdn.net/postcode/resource/images/close.png\" id=\"btnCloseLayer\" style=\"cursor:pointer;position:absolute;right:-3px;top:-3px;z-index:1\" onclick=\"closeDaumPostcode()\" alt=\"닫기 버튼\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    // 우편번호 찾기 화면을 넣을 element\r\n");
      out.write("    var element_layer = document.getElementById('layer');\r\n");
      out.write("\r\n");
      out.write("    function closeDaumPostcode() {\r\n");
      out.write("        // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("        element_layer.style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function sample2_execDaumPostcode() {\r\n");
      out.write("        new daum.Postcode({\r\n");
      out.write("            oncomplete: function(data) {\r\n");
      out.write("                // 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("                // 각 주소의 노출 규칙에 따라 주소를 조합한다.\r\n");
      out.write("                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("                var addr = ''; // 주소 변수\r\n");
      out.write("                var extraAddr = ''; // 참고항목 변수\r\n");
      out.write("\r\n");
      out.write("                //사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.\r\n");
      out.write("                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우\r\n");
      out.write("                    addr = data.roadAddress;\r\n");
      out.write("                } else { // 사용자가 지번 주소를 선택했을 경우(J)\r\n");
      out.write("                    addr = data.jibunAddress;\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 사용자가 선택한 주소가 도로명 타입일때 참고항목을 조합한다.\r\n");
      out.write("                if(data.userSelectedType === 'R'){\r\n");
      out.write("                    // 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("                    // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("                    if(data.bname !== '' && /[동|로|가]$/g.test(data.bname)){\r\n");
      out.write("                        extraAddr += data.bname;\r\n");
      out.write("                    }\r\n");
      out.write("                    // 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("                    if(data.buildingName !== '' && data.apartment === 'Y'){\r\n");
      out.write("                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);\r\n");
      out.write("                    }\r\n");
      out.write("                    // 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("                    if(extraAddr !== ''){\r\n");
      out.write("                        extraAddr = ' (' + extraAddr + ')';\r\n");
      out.write("                    }\r\n");
      out.write("                    // 조합된 참고항목을 해당 필드에 넣는다.\r\n");
      out.write("                    document.getElementById(\"sample2_extraAddress\").value = extraAddr;\r\n");
      out.write("                \r\n");
      out.write("                } else {\r\n");
      out.write("                    document.getElementById(\"sample2_extraAddress\").value = '';\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                // 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("                document.getElementById('sample2_postcode').value = data.zonecode;\r\n");
      out.write("                document.getElementById(\"sample2_address\").value = addr;\r\n");
      out.write("                // 커서를 상세주소 필드로 이동한다.\r\n");
      out.write("                document.getElementById(\"sample2_detailAddress\").focus();\r\n");
      out.write("\r\n");
      out.write("                // iframe을 넣은 element를 안보이게 한다.\r\n");
      out.write("                // (autoClose:false 기능을 이용한다면, 아래 코드를 제거해야 화면에서 사라지지 않는다.)\r\n");
      out.write("                element_layer.style.display = 'none';\r\n");
      out.write("            },\r\n");
      out.write("            width : '100%',\r\n");
      out.write("            height : '100%',\r\n");
      out.write("            maxSuggestItems : 5\r\n");
      out.write("        }).embed(element_layer);\r\n");
      out.write("\r\n");
      out.write("        // iframe을 넣은 element를 보이게 한다.\r\n");
      out.write("        element_layer.style.display = 'block';\r\n");
      out.write("\r\n");
      out.write("        // iframe을 넣은 element의 위치를 화면의 가운데로 이동시킨다.\r\n");
      out.write("        initLayerPosition();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    // 브라우저의 크기 변경에 따라 레이어를 가운데로 이동시키고자 하실때에는\r\n");
      out.write("    // resize이벤트나, orientationchange이벤트를 이용하여 값이 변경될때마다 아래 함수를 실행 시켜 주시거나,\r\n");
      out.write("    // 직접 element_layer의 top,left값을 수정해 주시면 됩니다.\r\n");
      out.write("    function initLayerPosition(){\r\n");
      out.write("        var width = 300; //우편번호서비스가 들어갈 element의 width\r\n");
      out.write("        var height = 400; //우편번호서비스가 들어갈 element의 height\r\n");
      out.write("        var borderWidth = 5; //샘플에서 사용하는 border의 두께\r\n");
      out.write("\r\n");
      out.write("        // 위에서 선언한 값들을 실제 element에 넣는다.\r\n");
      out.write("        element_layer.style.width = width + 'px';\r\n");
      out.write("        element_layer.style.height = height + 'px';\r\n");
      out.write("        element_layer.style.border = borderWidth + 'px solid';\r\n");
      out.write("        // 실행되는 순간의 화면 너비와 높이 값을 가져와서 중앙에 뜰 수 있도록 위치를 계산한다.\r\n");
      out.write("        element_layer.style.left = (((window.innerWidth || document.documentElement.clientWidth) - width)/2 - borderWidth) + 'px';\r\n");
      out.write("        element_layer.style.top = (((window.innerHeight || document.documentElement.clientHeight) - height)/2 - borderWidth) + 'px';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!--주소  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 네비게이션바 -->\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"header_container\">\r\n");
      out.write("\t\t\t<div class=\"header_content\">\r\n");
      out.write("\t\t\t\t<div class=\"logindiv\">\r\n");
      out.write("\t\t\t\t\t\t<a id=\"cart\"><img src=\"/TAMINO/image/cart.png\" width=\"20px\" height=\"20px\"></a>\r\n");
      out.write("\t\t\t\t\t\t<a id=\"login\" href=\"/TAMINO/StoreCtrl?command=login\">LOGIN</a>\r\n");
      out.write("\t\t\t\t\t\t<a id=\"mypage\" onclick=\"openNav()\">MY PAGE</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=StoreMain\"><img src=\"/TAMINO/image/storelogo.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"navbar\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=ProductList&category=all\">ALL</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=ProductList&category=clothing\">CLOTHIING</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=ProductList&category=accsesory\">ACCESORIES</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=ProductList&category=vinyl\">VINYL</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=ProductList&category=etc\">ETC</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"/TAMINO/ordercontrol?command=addorder\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"box1\">\t<!-- 전체 div -->\r\n");
      out.write("\r\n");
      out.write("<img height=\"250px\" width=\"100%\" src=\"../image/shop.jpg\">\r\n");
      out.write("\r\n");
      out.write("<h1>주문/결제</h1>\r\n");
      out.write("<br><br>\r\n");
      out.write("<div id=\"box2\" align=\"right\">\r\n");
      out.write("<pre class=\"steptext\">01장바구니><strong>02주문/결제</strong>>03주문완료 </pre>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");

/* 장바구니 정보 불러오기 */
List<OrderListDto> list = (List<OrderListDto>)session.getAttribute(mem.getEmail());

//전화번호 자르기
String phoneNum[] = { "010","011","016","017","018","019","070"};

String phone = mem.getPhoneNumber();
String phone1 = phone.split("-")[0];
String phone2 = phone.split("-")[1];
String phone3 = phone.split("-")[2];

String pickNum = phone1; 

//주소 자르기
String address = mem.getAddress();
String address1 = address.split("-")[0];
String address2 = address.split("-")[1];
String address3 = address.split("-")[2];
String address4 = address.split("-")[3];

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>배송지 정보</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("<input type=\"hidden\" name=\"order_email\" value=\"");
      out.print(mem.getEmail() );
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<div>   <!--  -->\r\n");
      out.write("<button type=\"button\" id=\"newbtn\">+새로운주소</button>\r\n");
      out.write("<table class=\"table1\">\r\n");
      out.write("\t<col width=\"20%\"><col width=\"80%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>이름</th><td><input type=\"text\" class=\"address\" name=\"order_name\" value=\"");
      out.print(mem.getUserName() );
      out.write("\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>연락처</th>\r\n");
      out.write("\t\t");

		
      out.write("\r\n");
      out.write("\t\t<td><select id=\"phone\" name=\"order_phonenumber1\" >\r\n");
      out.write("\t\t\t");

				for(int i=0; i<phoneNum.length; i++){
					if(phoneNum[i].equals(pickNum)){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(phoneNum[i]);
      out.write("\" selected=\"selected\">");
      out.print(phoneNum[i] );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t");

					}
					else{
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(phoneNum[i]);
      out.write('"');
      out.write('>');
      out.print(phoneNum[i] );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t");

					}
				}
			
      out.write("\r\n");
      out.write("\t\t\t</select> \r\n");
      out.write("\t\t - <input type=\"text\" class=\"address\" name=\"order_phonenumber2\"  maxlength=\"4\" value=\"");
      out.print(phone2 );
      out.write("\" numberOnly> - <input type=\"text\" class=\"address\"  name=\"order_phonenumber3\" maxlength=\"4\" value=\"");
      out.print(phone3 );
      out.write("\" numberOnly>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th rowspan=\"3\">주소</th><td><input type=\"text\" id=\"sample2_postcode\" class=\"address\" name=\"order_address1\" placeholder=\"우편번호\" value=\"");
      out.print(address1 );
      out.write("\" numberOnly readonly=\"readonly\">\r\n");
      out.write("\t<input type=\"button\" onclick=\"sample2_execDaumPostcode()\" class=\"adbtn\" id=\"postbtn\" value=\"우편번호 찾기\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><input type=\"text\" id=\"sample2_address\" class=\"address\" name=\"order_address2\" placeholder=\"주소\" value=\"");
      out.print(address2 );
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td><input type=\"text\" id=\"sample2_detailAddress\" name=\"order_address3\" class=\"address\" placeholder=\"상세주소\" value=\"");
      out.print(address3 );
      out.write("\">\r\n");
      out.write("\t<input type=\"text\" id=\"sample2_extraAddress\" class=\"address\" name=\"order_address4\" placeholder=\"참고항목\" value=\"");
      out.print(address4 );
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>배송 메모</th>\r\n");
      out.write("\t\t<td><select id=\"request\" name=\"order_request1\" class=\"address\">\r\n");
      out.write("\t\t<option value=\"배송 전에 미리 연락 바랍니다.\">배송 전에 미리 연락 바랍니다.</option>\r\n");
      out.write("\t\t<option value=\"부재시 경비실에 맡겨 주세요.\">부재시 경비실에 맡겨 주세요.</option>\r\n");
      out.write("\t\t<option value=\"부재시 전화 주시거나 문자 남겨 주세요.\">부재시 전화 주시거나 문자 남겨 주세요.</option> \r\n");
      out.write("\t\t<option value=\"\">직접입력 </option>\r\n");
      out.write("\t\t</select></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr><td></td><td><input type=\"text\" id=\"selboxDirect\" name=\"order_request2\" class=\"address\" placeholder=\"직접입력\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>주문상품 정보</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<table class=\"table1\" width=\"100%\">\r\n");
      out.write("<col width=\"15%\"><col width=\"40%\"><col width=\"10%\"><col width=\"10%\"><col width=\"20%\">\r\n");
      out.write("\t\r\n");
      out.write("\t<tr class=\"title\">\r\n");
      out.write("\t\t<th colspan=\"2\">상품정보</th><th>사이즈</th><th>수량</th><th>상품금액</th> <!-- 나중에 지우기 -->\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<input type=\"hidden\" name=\"listsize\" value=\"");
      out.print(list.size() );
      out.write("\">\r\n");
      out.write("\t\r\n");
      out.write("\t");

	DecimalFormat df = new DecimalFormat("###,###");  //
	
		for(int i = 0;i < list.size(); i++){
			OrderListDto dto = list.get(i);
			String image[] = dto.getProduct_image().split(",");
			String _price = df.format(dto.getProduct_price());	//
		
      out.write("\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"product_seq");
      out.print(i );
      out.write("\" value=\"");
      out.print(dto.getProduct_seq() );
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"product_price");
      out.print(i );
      out.write("\" value=\"");
      out.print(dto.getProduct_price());
      out.write("\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th class=\"lines\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"product_image");
      out.print(i );
      out.write("\" value=\"");
      out.print(dto.getProduct_image() );
      out.write("\">\r\n");
      out.write("\t\t\t\t<img src=\"/TAMINO/product/");
      out.print(image[0]);
      out.write("\" width=\"150px\" height=\"150px\">\r\n");
      out.write("\t\t\t</th>\r\n");
      out.write("\t\t\t<td class=\"lines\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"product_name");
      out.print(i );
      out.write("\" value=\"");
      out.print(dto.getProduct_name() );
      out.write("\">\r\n");
      out.write("\t\t\t\t");
      out.print(dto.getProduct_name() );
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"lines\" align=\"center\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"product_size");
      out.print(i );
      out.write("\" value=\"");
      out.print(dto.getProduct_size() );
      out.write("\">\r\n");
      out.write("\t\t\t\t");
      out.print(dto.getProduct_size() );
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td class=\"lines\" align=\"center\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"product_count");
      out.print(i );
      out.write("\" value=\"");
      out.print(dto.getProduct_count());
      out.write("\">\r\n");
      out.write("\t\t\t\t");
      out.print(dto.getProduct_count());
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td align=\"center\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"product_price");
      out.print(i );
      out.write("\" value=\"");
      out.print(dto.getProduct_price());
      out.write("\">\r\n");
      out.write("\t\t\t\t");
      out.print(_price);
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t");

	}
	
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("</table>\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");

int sum = 0;

for(int i = 0;i < list.size(); i++){
	OrderListDto dto = list.get(i);
	int price = dto.getProduct_price();
	int countitem = dto.getProduct_count();
	sum = sum + price*countitem;
}
int allsum = sum+2500;



String _sum = df.format(sum);	//
String _allsum = df.format(allsum);	//


      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("<div align=\"center\" class=\"title\">\r\n");
      out.write("<table id=\"mbox\" class=\"table1\">\r\n");
      out.write("<col width=\"500\"><col width=\"250\"><col width=\"250\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<th rowspan=\"2\"></th><td>상품금액</td><td>");
      out.print(_sum );
      out.write("원</td>\r\n");
      out.write("\t</tr> \r\n");
      out.write("\t\r\n");
      out.write("\t<tr >\r\n");
      out.write("\t<td>배송비</td><td>(+) 2,500원</td>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<th colspan=\"2\"><h2>총 주문금액</h2></th><td><h2>");
      out.print(_allsum );
      out.write("원</h2></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>결제</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("<div class=\"box5\" >\r\n");
      out.write("<table class=\"table\" id=\"cardinput\">\r\n");
      out.write("\t<col width=\"50%\"><col width=\"50%\">\r\n");
      out.write("\t<tr class=\"title\"><th colspan=\"2\">신용/직불카드</th></tr>\r\n");
      out.write("\t<tr class=\"title\"><th colspan=\"2\"><img class=\"cardimg\" src=\"../image/visa.png\"><img class=\"cardimg\" src=\"../image/mastercard.jpg\"><img class=\"cardimg\" src=\"../image/jcb.png\"></th></tr>\r\n");
      out.write("\t<tr class=\"title\"><td colspan=\"2\">카드 명의자 이름(영문)</td></tr>\r\n");
      out.write("\t<tr><td colspan=\"2\"><input type=\"text\" id=\"cardname\"  onkeyup=\"this.value=this.value.replace(/[^a-zA-Z]/g,'');\"></td></tr>\r\n");
      out.write("\t<tr class=\"title\"><td colspan=\"2\">신용/직불카드 번호</td></tr>\r\n");
      out.write("\t<tr><td colspan=\"2\"><input type=\"text\" id=\"cardnumber\" maxlength=\"16\" numberOnly></td></tr>\r\n");
      out.write("\t<tr class=\"title\"><td>카드 유효기간</td>  <td> cvc/cvv</td></tr>\r\n");
      out.write("\t<tr><td><input type=\"text\" placeholder=\"mm/yy\" maxlength=\"4\" id=\"carddate\" numberOnly></td><td><input type=\"password\" maxlength=\"3\" id=\"cvc\"></td></tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("<div class=\"box5\" id=\"box6\">\r\n");
      out.write("<img id=\"cardbig\" src=\"../image/cvc.png\" style=\"margin-left: 10px\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\" style=\"margin-top: 13rem;\">\r\n");
      out.write("<button class=\"btn2\" id=\"btn3\" style=\"margin-right: 5rem;\">취소</button><input type=\"submit\" class=\"btn2\" id=\"btn4\" value=\"결제하기\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div><!-- 전체 div -->\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"myNav\" class=\"overlay\">\r\n");
      out.write("<a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\r\n");
      out.write("\t<div class=\"overlay-content\">\r\n");
      out.write("\t\t<p>MY PAGE</p>\r\n");
      out.write("    \t<a href=\"/TAMINO/MemberCtrl?command=myInfo&email=");
      out.print(currId );
      out.write("\">회원정보 수정</a>\r\n");
      out.write("    \t<a href=\"/TAMINO/MemberCtrl?command=MyOrderList\">주문내역</a>\r\n");
      out.write("  \t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<a href=\"http://instagram.com/taminoamir\" target=\"_blank\"><img src=\"/TAMINO/image/instagram.png\" style=\"width: 30px; height: 30px;\"></a>\r\n");
      out.write("\t<a href=\"https://twitter.com/taminoamir\" target=\"_blank\"><img src=\"/TAMINO/image/twitter.png\" style=\"width: 30px; height: 30px;\"></a>\r\n");
      out.write("\t<a href=\"https://www.facebook.com/taminoamir/?ref=br_rs\" target=\"_blank\"><img src=\"/TAMINO/image/facebook.png\" style=\"width: 30px; height: 30px;\"></a>\r\n");
      out.write("\t<a href=\"https://www.youtube.com/channel/UCzoO5qFoT-7w7o7f1QqhOpA\" target=\"_blank\"><img src=\"/TAMINO/image/youtube.png\" style=\"width: 30px; height: 30px;\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <script language=\"javascript\"> \r\n");
      out.write("\r\n");
      out.write(" $(function confirmtest(){\r\n");
      out.write("\t $(\"#btn3\").mousedown(function() {\r\n");
      out.write("\t\t location.href = \"/TAMINO/StoreCtrl?command=goCart\";\r\n");
      out.write("\t});\r\n");
      out.write(" });\r\n");
      out.write(" $(function(){\r\n");
      out.write("$(\"#selboxDirect\").hide();\r\n");
      out.write("$(\"#request\").change(function() {\r\n");
      out.write("               //직접입력을 누를 때 나타남\r\n");
      out.write("\t\tif($(\"#request\").val() == \"\") {\r\n");
      out.write("\t\t\t$(\"#selboxDirect\").show();\r\n");
      out.write("\t\t}  else {\r\n");
      out.write("\t\t\t$(\"#selboxDirect\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}) \r\n");
      out.write("}); \r\n");
      out.write("\r\n");
      out.write(" \"#carddate\" \r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function () {\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#newbtn\").mousedown(function() {\r\n");
      out.write("\t\t$(\".address\").val(\"\"); //새로운주소\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#newbtn\").mouseover(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"background\", \"#AAABD3\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#newbtn\").mouseout(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"background\", \"black\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".btn2\").mouseover(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"background\", \"#AAABD3\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".btn2\").mouseout(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"background\", \"black\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#postbtn\").mouseover(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"background\", \"#AAABD3\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#postbtn\").mouseout(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"background\", \"black\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"input:text[numberOnly]\").on(\"keyup\", function() {\r\n");
      out.write("\t    $(this).val($(this).val().replace(/[^0-9]/g,\"\"));\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#btn4\").mousedown(function() {\r\n");
      out.write("\t\tif($(\"#cardname\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"카드 명의자 이름을 입력해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}else if($(\"#cardnumber\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"신용/직불카드 번호를 입력해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}else if($(\"#carddate\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"카드 유효기간을 입력해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}else if($(\"#cvc\").val()==\"\"){\r\n");
      out.write("\t\t\talert(\"cvc/cvv를 입력해주세요\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function () {\r\n");
      out.write("\tif($(\"#currId\").val() != \"guest\"){\r\n");
      out.write("\t\t//alert($(\"#login\").attr(\"href\"));\r\n");
      out.write("\t\t$(\"#login\").text(\"LOGOUT\");\r\n");
      out.write("\t\t$(\"#login\").attr(\"href\", \"/TAMINO/StoreCtrl?command=logout\");\r\n");
      out.write("\t\t$(\"#mypage\").css(\"display\", \"block\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#cart\").click(function() {\r\n");
      out.write("\t\tif($(\"#currId\").val() == \"guest\"){/* 로그인 하지 않은 경우 */\r\n");
      out.write("\t\t\talert(\"장바구니는 로그인 후 이용 가능합니다.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//location.href = \"/TAMINO/StoreCtrl?command=login\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#cart\").attr(\"href\", \"/TAMINO/StoreCtrl?command=goCart\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function openNav() {\r\n");
      out.write("  document.getElementById(\"myNav\").style.width = \"100%\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeNav() {\r\n");
      out.write("  document.getElementById(\"myNav\").style.width = \"0%\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"scrollevent.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
