/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2020-03-19 12:53:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Store;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.text.DecimalFormat;
import dto.MemberDto;
import dto.OrderListDto;
import java.util.List;

public final class Store_005fOrderResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.text.DecimalFormat");
    _jspx_imports_classes.add("dto.MemberDto");
    _jspx_imports_classes.add("dto.OrderListDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

MemberDto logindto = (MemberDto)session.getAttribute("login");
	String currId = "guest";
	if( request.getSession().getAttribute("login") != null ){
		MemberDto loginDto = (MemberDto)request.getSession().getAttribute("login");
		currId = loginDto.getEmail();
	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("font-family: 'Open Sans', sans-serif;\r\n");
      out.write("width:100%; \r\n");
      out.write("text-align:left;\r\n");
      out.write("background-size: 100%;\r\n");
      out.write("background-repeat: no-repeat;\r\n");
      out.write("}\r\n");
      out.write("#box1{\r\n");
      out.write("\t  width: 60%;\r\n");
      out.write("\t    height:auto;\r\n");
      out.write("\t   margin: 0 auto;\r\n");
      out.write("\t   margin-top: 200px;\r\n");
      out.write("\t   margin-bottom: 100px;\r\n");
      out.write("\t   padding-bottom: 200px;\r\n");
      out.write("/* \t border: solid 1px;\r\n");
      out.write("\t border-color: red; */\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".table1 {\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("    border-top: 1px solid #6C6C6C;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("th, td {\r\n");
      out.write("    border-bottom: 1px solid #6C6C6C;\r\n");
      out.write("     padding: 10px; \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".newbtn{\r\n");
      out.write("margin-top:15px;\r\n");
      out.write("width:300px;\r\n");
      out.write("height:50px;\r\n");
      out.write("font-size:1.5em;\r\n");
      out.write("background-color: black;\r\n");
      out.write("color: white;\r\n");
      out.write("border: none;\r\n");
      out.write("font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#table1 td{\r\n");
      out.write("text-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item{\r\n");
      out.write("height: 150px;\r\n");
      out.write("width: 150px;\r\n");
      out.write("}\r\n");
      out.write("#title1{\r\n");
      out.write("color: white;\r\n");
      out.write("background-color: #212121;\r\n");
      out.write("}\r\n");
      out.write("#title2{\r\n");
      out.write("background-color: #EAEAEA;\r\n");
      out.write("}\r\n");
      out.write(".steptext{\r\n");
      out.write("\tfont-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("\tfont-size: 11pt;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!-- 네비게이션바 -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/TAMINO/Store/css/Store_List.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/TAMINO/Store/css/MyPageOverlay.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR|Roboto|Roboto+Mono|Viga&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- 네비게이션바 -->\r\n");
      out.write("<input type=\"hidden\" value=\"");
      out.print(currId );
      out.write("\" id=\"currId\"> \r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("\t\t<div class=\"header_container\">\r\n");
      out.write("\t\t\t<div class=\"header_content\">\r\n");
      out.write("\t\t\t\t<div class=\"logindiv\">\r\n");
      out.write("\t\t\t\t\t\t<a id=\"cart\"><img src=\"/TAMINO/image/cart.png\" width=\"20px\" height=\"20px\"></a>\r\n");
      out.write("\t\t\t\t\t\t<a id=\"login\" href=\"/TAMINO/MemberCtrl?command=login\">LOGIN</a>\r\n");
      out.write("\t\t\t\t\t\t<a id=\"mypage\" onclick=\"openNav()\">MY PAGE</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=StoreMain\"><img src=\"/TAMINO/image/storelogo.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"navbar\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=ProductList&category=all\">ALL</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=ProductList&category=clothing\">CLOTHIING</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=ProductList&category=accsesory\">ACCESORIES</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=ProductList&category=vinyl\">VINYL</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=ProductList&category=etc\">ETC</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"/TAMINO/Store/scrollevent.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

List<OrderListDto> list = (List<OrderListDto>)request.getAttribute("orderlist");
String today = (String)request.getAttribute("_today");
today = today.substring(0, 8);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"box1\">\t<!-- 전체 div -->\r\n");
      out.write("\r\n");
      out.write("<img height=\"250px\" width=\"100%\" src=\"/TAMINO/image/shop.jpg\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br><br>\r\n");
      out.write("<h3></h3>\r\n");
      out.write("<h2 align=\"center\">주문/결제가 완료되었습니다</h2>\r\n");
      out.write("<br><br>\r\n");
      out.write("<div id=\"box2\" align=\"right\">\r\n");
      out.write("<pre class=\"steptext\">01장바구니>02주문/결제><strong>03주문완료</strong> </pre>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");

DecimalFormat df = new DecimalFormat("###,###");  //
int sum = 0;
for(int i = 0;i < list.size(); i++){
	OrderListDto dto = list.get(i);
	int price = dto.getProduct_price();
	int countitem = dto.getProduct_count();
	sum = sum + price*countitem;

}
int allsum = sum+2500;

String _sum = df.format(sum);	//
String _allsum = df.format(allsum);	//

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<h3>주문상품 정보</h3>\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("<table class=\"table1\">\r\n");
      out.write("<col width=\"150\"><col width=\"450\">\r\n");
      out.write("\t\r\n");
      out.write("\t<tr id=\"title1\"><td colspan=\"2\"> ");
      out.print(today );
      out.write("</td></tr>\r\n");
      out.write(" \t");

	System.out.println("Store_OrderResult.jsp 넘어온 list길이"+list.size());
	for(int i = 0;i < list.size(); i++){
		OrderListDto dto = list.get(i);
		String image[] = dto.getProduct_image().split(",");
		String _price = df.format(dto.getProduct_price());	//
		
      out.write("\r\n");
      out.write("\t<tr><th rowspan=\"3\"><img src=\"/TAMINO/product/");
      out.print(image[0]);
      out.write("\" class=\"item\"> </th><td>");
      out.print(dto.getProduct_name() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><td>[옵션]사이즈:");
      out.print(dto.getProduct_size() );
      out.write("</td></tr>\r\n");
      out.write("\t<tr><td>");
      out.print(_price );
      out.write('원');
      out.write('/');
      out.write(' ');
      out.print(dto.getProduct_count() );
      out.write("개</td></tr>\r\n");
      out.write("\t");

	}
	
      out.write(" \r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<table class=\"table1\" id=\"title2\">\r\n");
      out.write("<col width=\"50%\"><col width=\"25%\"><col width=\"25%\">\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<th rowspan=\"2\"></th><th>상품가격</th><td>");
      out.print(_sum );
      out.write("원</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<th>배송비</th><td>2,500원</td>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t<th colspan=\"2\" ><h2>총 주문금액</h2></th><td><h2>");
      out.print(_allsum );
      out.write("원</h2></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("</div>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<button class=\"newbtn\">Shop 홈으로</button>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- <button class=\"btn\">나의 주문내역</button>  --> <!-- 확인용 연결후 지우기 -->\r\n");
      out.write("</div><!-- 전체 div -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div id=\"myNav\" class=\"overlay\">\r\n");
      out.write("<a href=\"javascript:void(0)\" class=\"closebtn\" onclick=\"closeNav()\">&times;</a>\r\n");
      out.write("\t<div class=\"overlay-content\">\r\n");
      out.write("\t\t<p>MY PAGE</p>\r\n");
      out.write("    \t<a href=\"/TAMINO/MemberCtrl?command=myInfo&email=");
      out.print(currId );
      out.write("\">회원정보 수정</a>\r\n");
      out.write("    \t<a href=\"/TAMINO/MemberCtrl?command=MyOrderList\">주문내역</a>\r\n");
      out.write("  \t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- footer -->\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("\t<a href=\"http://instagram.com/taminoamir\" target=\"_blank\"><img src=\"/TAMINO/image/instagram.png\" style=\"width: 30px; height: 30px;\"></a>\r\n");
      out.write("\t<a href=\"https://twitter.com/taminoamir\" target=\"_blank\"><img src=\"/TAMINO/image/twitter.png\" style=\"width: 30px; height: 30px;\"></a>\r\n");
      out.write("\t<a href=\"https://www.facebook.com/taminoamir/?ref=br_rs\" target=\"_blank\"><img src=\"/TAMINO/image/facebook.png\" style=\"width: 30px; height: 30px;\"></a>\r\n");
      out.write("\t<a href=\"https://www.youtube.com/channel/UCzoO5qFoT-7w7o7f1QqhOpA\" target=\"_blank\"><img src=\"/TAMINO/image/youtube.png\" style=\"width: 30px; height: 30px;\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("\t$(\".newbtn\").mousedown(function() {\r\n");
      out.write("\t\t//\talert(\"mousedown\");\r\n");
      out.write("\t\t\tlocation.href = \"/TAMINO/StoreCtrl?command=StoreMain\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\t$(\".newbtn\").mouseover(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"background\", \"#AAABD3\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".newbtn\").mouseout(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"background\", \"black\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".btn\").mousedown(function() {\r\n");
      out.write("\t\t//\talert(\"mousedown\");\r\n");
      out.write("\t\t\tlocation.href = \"/TAMINO/StoreCtrl?command=MyOrderList\";\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(function () {\r\n");
      out.write("\tif($(\"#currId\").val() != \"guest\"){\r\n");
      out.write("\t\t//alert($(\"#login\").attr(\"href\"));\r\n");
      out.write("\t\t$(\"#login\").text(\"LOGOUT\");\r\n");
      out.write("\t\t$(\"#login\").attr(\"href\", \"/TAMINO/StoreCtrl?command=logout\");\r\n");
      out.write("\t\t$(\"#mypage\").css(\"display\", \"block\");\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#cart\").click(function() {\r\n");
      out.write("\t\tif($(\"#currId\").val() == \"guest\"){/* 로그인 하지 않은 경우 */\r\n");
      out.write("\t\t\talert(\"장바구니는 로그인 후 이용 가능합니다.\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//location.href = \"/TAMINO/StoreCtrl?command=login\";\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#cart\").attr(\"href\", \"/TAMINO/StoreCtrl?command=goCart\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function openNav() {\r\n");
      out.write("  document.getElementById(\"myNav\").style.width = \"100%\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeNav() {\r\n");
      out.write("  document.getElementById(\"myNav\").style.width = \"0%\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("     \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
