/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2020-03-19 12:54:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.News;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dto.MemberDto;
import dto.NewsDto;
import java.util.List;

public final class Newsvideo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dto.NewsDto");
    _jspx_imports_classes.add("dto.MemberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
 
 
	Object ologin = session.getAttribute("login");
	MemberDto mdto = null;
	mdto = (MemberDto)ologin;
 
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=DM+Serif+Text|Roboto+Condensed&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/TAMINO/News/Navibar.css?after\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR|Roboto|Roboto+Mono|Viga&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write(" background-color: black; \r\n");
      out.write("font-family: 'Roboto', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box1{\r\n");
      out.write("overflow:hidden;\r\n");
      out.write("  width: 60%;\r\n");
      out.write("   height:auto;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   margin-top: 200px;\r\n");
      out.write("   margin-bottom: 50px;\r\n");
      out.write("/*    padding-bottom: 50px;\r\n");
      out.write("  border: solid 2px; */\r\n");
      out.write(" border-color: red;  \r\n");
      out.write("padding-top: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box2{\r\n");
      out.write("overflow:hidden;\r\n");
      out.write("  width: 1000px;\r\n");
      out.write("   height:auto;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   margin-top: 50px;\r\n");
      out.write("   margin-bottom: 50px;\r\n");
      out.write("   padding-bottom: 50px;\r\n");
      out.write("/*   border: solid 2px;\r\n");
      out.write(" border-color: blue;  */\r\n");
      out.write(" text-align: center;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".box3 {\r\n");
      out.write("\r\n");
      out.write("float:left; /* 옆으로 붙게 */\r\n");
      out.write("margin: 20px auto;\r\n");
      out.write("margin-left:10px;\r\n");
      out.write("margin-right:10px;\r\n");
      out.write("  width:480px;\r\n");
      out.write("  height:400px;\r\n");
      out.write(" \r\n");
      out.write("/*  border-color: gray;  */\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".minititle{\r\n");
      out.write("text-shadow: -1px 0 #F2F1F6, 0 1px #F2F1F6, 1px 0 #F2F1F6, 0 -1px #F2F1F6;\r\n");
      out.write("-moz-text-shadow: -1px 0 #F2F1F6, 0 1px #F2F1F6, 1px 0 #F2F1F6, 0 -1px #F2F1F6;\r\n");
      out.write("-webkit-text-shadow: -1px 0 #F2F1F6, 0 1px #F2F1F6, 1px 0 #F2F1F6, 0 -1px #F2F1F6;\r\n");
      out.write("}\r\n");
      out.write(".imgDiv:hover{\r\n");
      out.write("filter:blur(3px);\r\n");
      out.write("-webkit-filter:blur(3px);\r\n");
      out.write("}\r\n");
      out.write("   /* 큰 video */\r\n");
      out.write(".bigbox{\r\n");
      out.write("\r\n");
      out.write(" overflow:hidden;\r\n");
      out.write(" position: relative;\r\n");
      out.write("margin: 0 auto;\r\n");
      out.write("width: 100%;\r\n");
      out.write("height: 100%;\r\n");
      out.write("/*  border: solid 1px;\r\n");
      out.write("border-color: aqua; */\r\n");
      out.write("margin-bottom: 100px;\r\n");
      out.write("text-align: center;\r\n");
      out.write("}   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write(".content{\r\n");
      out.write("font-size: 20px;\r\n");
      out.write("color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 미니 메뉴바 부분 */\r\n");
      out.write(".minimenu{\r\n");
      out.write("width:300px;\r\n");
      out.write("border: solid;\r\n");
      out.write("text-align: center;\r\n");
      out.write("margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#photo{\r\n");
      out.write("float: left;\r\n");
      out.write("font-size: 40px;\r\n");
      out.write("color: white;\r\n");
      out.write("cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#video{\r\n");
      out.write("font-size: 40px;\r\n");
      out.write("color: #e77e4d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#title{\r\n");
      out.write("color: white;\r\n");
      out.write("font-size: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".news_img{ /* 큰화면 video */\r\n");
      out.write("width: 100%;\r\n");
      out.write("height: 55%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#load{\r\n");
      out.write("color: white;\r\n");
      out.write("font-size: 30px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* 이미지 올라가는 효과 */\r\n");
      out.write("  .imgBoxDiv{\r\n");
      out.write("\r\n");
      out.write("      width: 475px;\r\n");
      out.write("      height: 375px;\r\n");
      out.write("      position: relative;\r\n");
      out.write("      cursor: pointer;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("      box-shadow: 2px 2px 8px 0px #000;\r\n");
      out.write("    }\r\n");
      out.write("    .imgDiv{\r\n");
      out.write("      width: 100%;\r\n");
      out.write("      height: 100%;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      z-index:0;\r\n");
      out.write("      -webkit-transition:all .5s ease;\r\n");
      out.write("      transition: all .5s ease;\r\n");
      out.write("      bottom:0px;\r\n");
      out.write("      overflow: hidden;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     .imgBoxDiv:hover .imgDiv{\r\n");
      out.write("       bottom: 60px;\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("     .imgDescDiv{\r\n");
      out.write("      width: 99%; \r\n");
      out.write("      height: 70px;\r\n");
      out.write("      padding-top:12px;\r\n");
      out.write("      margin-left:2px;\r\n");
      out.write("      color:black;\r\n");
      out.write("      z-index:-1;\r\n");
      out.write("      background: rgba(175,225,255,0.2);\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      bottom:0px;\r\n");
      out.write("      font-size: 20px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 모달 */\r\n");
      out.write("  .modal {\r\n");
      out.write("            display: none; /* Hidden by default */\r\n");
      out.write("            position: fixed; /* Stay in place */\r\n");
      out.write("            z-index: 1; /* Sit on top */\r\n");
      out.write("            left: 0;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            width: 100%; /* Full width */\r\n");
      out.write("            height: 100%; /* Full height */\r\n");
      out.write("            overflow: auto; /* Enable scroll if needed */\r\n");
      out.write("           background-color: white;\r\n");
      out.write("           background-color: rgba( 255, 255, 255, 0.5 );\r\n");
      out.write("          \r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* Modal Content/Box */\r\n");
      out.write("        .modal-content {\r\n");
      out.write("        \tpadding-top:100px;\r\n");
      out.write("            text-align:center;\r\n");
      out.write("            \r\n");
      out.write("            border: 1px solid #888;\r\n");
      out.write("         \twidth: 100%; /* Could be more or less, depending on screen size */ \r\n");
      out.write("            height: 75%;\r\n");
      out.write("        }\r\n");
      out.write("        /* The Close Button */\r\n");
      out.write("        .close {\r\n");
      out.write("            color: black;\r\n");
      out.write("           \r\n");
      out.write("            font-size: 50px;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("        }\r\n");
      out.write("        .close:hover,\r\n");
      out.write("        .close:focus {\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write(".captions{\r\n");
      out.write("\tfont-size: 30pt;\r\n");
      out.write("\tmargin-left: 3rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

List<NewsDto> list = (List<NewsDto>)request.getAttribute("newslist");

      out.write(" \r\n");
      out.write("\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<div class=\"header\" style=\"background-color: rgba(255,255,255,0.5)\">\r\n");
      out.write("\t\t<div class=\"header_container\">\r\n");
      out.write("\t\t\t<div class=\"header_content\">\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/AdminCtrl?command=Main_Page\"><img src=\"/TAMINO/image/logo.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"navbar\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/newscontrol?command=list\">NEWS</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/ScheduleCtrl?command=schedule\">SCHEDULE</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=StoreMain\">STORE</a>\r\n");
      out.write("\t\t\t\t\t\t");

							if(mdto != null){
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/TAMINO/MemberCtrl?command=logout\">LOGOUT</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

							}
							else{
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/TAMINO/MemberCtrl?command=login\">LOGIN</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
								
							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<form action=\"/TAMINO/AdminCtrl\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"command\" value=\"addvideo\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"box1\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"minimenu\"><div class=\"menu\" id=\"photo\"><p class=\"captions\">PHOTOS</p></div><div class=\"menu\" id=\"video\"><p class=\"captions\">VIDEOS</p></strong></div></div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"box2\">\r\n");
      out.write("\r\n");
      out.write("<!-- video첫번째칸 -->\r\n");
      out.write("<div class=\"bigbox\">\r\n");
 NewsDto fdto = list.get(0); 
	if(fdto.getDel() == 0){  

      out.write("\t\r\n");
      out.write(" <!-- Trigger/Open The Modal -->\r\n");
      out.write("    <div>");
      out.print(fdto.getContent() );
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write(" \t<p id=\"title\">");
      out.print(fdto.getTitle() );
      out.write("</p>\r\n");
 } 
      out.write("\r\n");
      out.write("</div>\t<!-- bigbox -->\r\n");
      out.write("\r\n");

for(int i = 1;i < list.size(); i++){
	NewsDto dto = list.get(i);
		if(dto.getDel() == 0){  
		
      out.write("\t\r\n");
      out.write("<div class=\"box3\" style=\"display: none;\">\r\n");
      out.write(" <!-- Trigger/Open The Modal -->\r\n");
      out.write("    <a class=\"btn\">\r\n");
      out.write("\t    <div class=\"imgBoxDiv\">\r\n");
      out.write("\t    <div class=\"imgDiv\">\r\n");
      out.write("\t    \t<img src=\"./upload/");
      out.print(dto.getFilename() );
      out.write("\" width=\"475\" height=\"375\" alt=\"\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <div class=\"imgDescDiv\"><p class=\"minititle\">");
      out.print(dto.getTitle() );
      out.write("</p></div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("    </a>\r\n");
      out.write(" \t\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- The Modal -->\r\n");
      out.write("<div class=\"modal\">    \r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <!-- Modal content -->\r\n");
      out.write("        <span class=\"close\">&times;</span>                                                               \r\n");
      out.write("        <p>");
      out.print(dto.getContent() );
      out.write("</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\t  \r\n");
      out.write("\t</div>  <!-- box3 -->   \r\n");
      out.write("\t");
 
	}
}

      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</div>\t<!-- div2 -->\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<a href=\"#\" id=\"load\">View More Videos</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>  <!-- div1 -->\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("//Modal을 가져옵니다.\r\n");
      out.write("var modals = document.getElementsByClassName(\"modal\");                       \r\n");
      out.write("//Modal을 띄우는 클래스 이름을 가져옵니다.\r\n");
      out.write("var btns = document.getElementsByClassName(\"btn\");\r\n");
      out.write("//Modal을 닫는 close 클래스를 가져옵니다.\r\n");
      out.write("var spanes = document.getElementsByClassName(\"close\");\r\n");
      out.write("var funcs = [];\r\n");
      out.write("\r\n");
      out.write("//Modal을 띄우고 닫는 클릭 이벤트를 정의한 함수\r\n");
      out.write("function Modal(num) {\r\n");
      out.write("return function() {\r\n");
      out.write(" // 해당 클래스의 내용을 클릭하면 Modal을 띄웁니다.\r\n");
      out.write(" btns[num].onclick =  function() {\r\n");
      out.write("     modals[num].style.display = \"block\";\r\n");
      out.write("     console.log(num);\r\n");
      out.write(" };\r\n");
      out.write("\r\n");
      out.write(" // <span> 태그(X 버튼)를 클릭하면 Modal이 닫습니다.\r\n");
      out.write(" spanes[num].onclick = function() {\r\n");
      out.write("     modals[num].style.display = \"none\";\r\n");
      out.write(" };\r\n");
      out.write("};\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//원하는 Modal 수만큼 Modal 함수를 호출해서 funcs 함수에 정의합니다.\r\n");
      out.write("for(var i = 0; i < btns.length; i++) {\r\n");
      out.write("funcs[i] = Modal(i);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//원하는 Modal 수만큼 funcs 함수를 호출합니다.\r\n");
      out.write("for(var j = 0; j < btns.length; j++) {\r\n");
      out.write("funcs[j]();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//Modal 영역 밖을 클릭하면 Modal을 닫습니다.\r\n");
      out.write("window.onclick = function(event) {\r\n");
      out.write("if (event.target.className == \"modal\") {\r\n");
      out.write("   event.target.style.display = \"none\";\r\n");
      out.write("}\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#photo\").mouseover(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"color\", \"#e77e4d\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#photo\").mouseout(function() {\r\n");
      out.write("\t\t$(this).css(\"color\", \"white\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#photo\").mousedown(function() {\r\n");
      out.write("\t\tlocation.href = \"/TAMINO/newscontrol?command=list\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function () { /* 갯수대로 자르기 */\r\n");
      out.write("\r\n");
      out.write("\t$(\".box3\").slice(0,4).show();\r\n");
      out.write("\t$(\"#load\").click(function(e) {\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\t$(\".box3:hidden\").slice(0,4).show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\".box3:hidden\").length==0){\r\n");
      out.write("\t\t\t$(\"#load\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
