/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.42
 * Generated at: 2020-03-19 12:22:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.News;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dto.MemberDto;
import dto.NewsDto;
import java.util.List;

public final class Newslist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dto.NewsDto");
    _jspx_imports_classes.add("dto.MemberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
 
	Object ologin = session.getAttribute("login");
	MemberDto mdto = null;
	mdto = (MemberDto)ologin;
 
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>News</title>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=DM+Serif+Text|Roboto+Condensed&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Noto+Sans+KR|Roboto|Roboto+Mono|Viga&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/TAMINO/News/Navibar.css?after\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body{\r\n");
      out.write("background-color: black;\r\n");
      out.write("font-family: 'Roboto', sans-serif;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box1{\r\n");
      out.write("overflow:hidden;\r\n");
      out.write("  width: 1200px;\r\n");
      out.write("   height:auto;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   margin-top: 200px;\r\n");
      out.write("   margin-bottom: 50px;\r\n");
      out.write("   padding-bottom: 50px;\r\n");
      out.write("/*   border: solid 2px;\r\n");
      out.write(" border-color: red;  */\r\n");
      out.write("padding-top: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#box2{\r\n");
      out.write("overflow:hidden;\r\n");
      out.write("  width: 1100px;\r\n");
      out.write("   height:auto;\r\n");
      out.write("   margin: 0 auto;\r\n");
      out.write("   margin-top: 50px;\r\n");
      out.write("   margin-bottom: 50px;\r\n");
      out.write("   padding-bottom: 50px;\r\n");
      out.write("/*  border: solid 2px;\r\n");
      out.write(" border-color: blue; */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".box3 {\r\n");
      out.write("float:left; /* 옆으로 붙게 */\r\n");
      out.write("  width:360px;\r\n");
      out.write("  height: 550px;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("/*  border-color: gray; */\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .box4 {\r\n");
      out.write("   background-color: white;\r\n");
      out.write("   overflow:hidden;\r\n");
      out.write("   height : 500px;\r\n");
      out.write(" position: relative;\r\n");
      out.write(" float: left;\r\n");
      out.write(" margin:20px;\r\n");
      out.write("/*   border: solid 7px;\r\n");
      out.write(" border-color: green; */\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write(".box4 {\r\n");
      out.write("  transform: scale(1);\r\n");
      out.write("  -webkit-transform: scale(1);\r\n");
      out.write("  -moz-transform: scale(1);\r\n");
      out.write("  -ms-transform: scale(1);\r\n");
      out.write("  -o-transform: scale(1);\r\n");
      out.write("  transition: all 0.3s ease-in-out;   /* 부드러운 모션을 위해 추가*/\r\n");
      out.write("}\r\n");
      out.write(".box4:hover {\r\n");
      out.write("  transform: scale(1.1);\r\n");
      out.write("  -webkit-transform: scale(1.1);\r\n");
      out.write("  -moz-transform: scale(1.1);\r\n");
      out.write("  -ms-transform: scale(1.1);\r\n");
      out.write("  -o-transform: scale(1.1);\r\n");
      out.write("}   \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write(".news_img{ \r\n");
      out.write("width: 100%;\r\n");
      out.write("height: 55%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text{\r\n");
      out.write("padding-left: 10px;\r\n");
      out.write("padding-right: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#load{\r\n");
      out.write("color: white;\r\n");
      out.write("font-size: 30px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 미니 메뉴바 부분 */\r\n");
      out.write(".minimenu{\r\n");
      out.write("width:300px;\r\n");
      out.write("border: solid;\r\n");
      out.write("text-align: center;\r\n");
      out.write("margin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#photo{\r\n");
      out.write("float: left;\r\n");
      out.write("font-size: 40px;\r\n");
      out.write("color: #e77e4d;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#video{\r\n");
      out.write("font-size: 40px;\r\n");
      out.write("color: white;\r\n");
      out.write("cursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".captions{\r\n");
      out.write("\tfont-size: 30pt;\r\n");
      out.write("\tmargin-left: 3rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- header -->\r\n");
      out.write("<div class=\"header\" style=\"background-color: rgba(255,255,255,0.5)\">\r\n");
      out.write("\t\t<div class=\"header_container\">\r\n");
      out.write("\t\t\t<div class=\"header_content\">\r\n");
      out.write("\t\t\t\t<div class=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/AdminCtrl?command=Main_Page\"><img src=\"/TAMINO/image/logo.png\"></a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div class=\"navbar\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/newscontrol?command=list\">NEWS</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/ScheduleCtrl?command=schedule\">SCHEDULE</a>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/TAMINO/StoreCtrl?command=StoreMain\">STORE</a>\r\n");
      out.write("\t\t\t\t\t\t");

							if(mdto != null){
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/TAMINO/MemberCtrl?command=logout\">LOGOUT</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");

							}
							else{
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"/TAMINO/MemberCtrl?command=login\">LOGIN</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t");
								
							}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write(" <!-- 로그인정보 불러오기 만들기 -->\r\n");
      out.write("\r\n");

List<NewsDto> list = (List<NewsDto>)request.getAttribute("newslist");

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"/TAMINO/AdminCtrl\" method=\"post\">\r\n");
      out.write("<input type=\"hidden\" name=\"command\" value=\"write\">\r\n");
      out.write("\r\n");
      out.write("<div id=\"box1\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"minimenu\"><div class=\"menu\" id=\"photo\"><p class=\"captions\">PHOTOS</p></div><div class=\"menu\" id=\"video\"><p class=\"captions\">VIDEOS</p></div></div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"box2\">\r\n");
      out.write("\r\n");


for(int i = 0;i < list.size(); i++){
	NewsDto dto = list.get(i);
			//글자수 자르기
			String txt = dto.getContent();
			if(txt.length() >= 180){
			    txt = txt.substring(0,180)+"...";
			    }
		if(dto.getDel() == 0){  
			
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"box3\" style=\"display: none;\">\r\n");
      out.write("\t\t<div class=\"box4\" seq=");
      out.print(dto.getNews_seq() );
      out.write(">\r\n");
      out.write("\t\t\t<img class=\"news_img\" src=\"./upload/");
      out.print(dto.getFilename() );
      out.write("\">\r\n");
      out.write("\t\t\t<div class=\"text\">\r\n");
      out.write("\t\t\t\t<h2>");
      out.print(dto.getTitle() );
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<p>");
      out.print(txt );
      out.write("</p><!-- 글자수 제한 -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t  \r\n");
      out.write("\t   \r\n");
      out.write("\t \r\n");
      out.write("\t");
 
	}
}

      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("<a href=\"#\" id=\"load\">View More Photos</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".box4\").mousedown(function() {\r\n");
      out.write("\t//\talert(\"mousedown\");\r\n");
      out.write("\t\tlocation.href = \"/TAMINO/newscontrol?command=detail&seq=\" + $(this).attr(\"seq\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".box4\").mouseover(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"background\", \"#e0e0e0\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\".box4\").mouseout(function() {\r\n");
      out.write("\t\t$(this).css(\"background\", \"#ffffff\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#video\").mouseover(function() {\t\t\r\n");
      out.write("\t\t$(this).css(\"color\", \"#e77e4d\");\r\n");
      out.write("\t});\r\n");
      out.write("\t$(\"#video\").mouseout(function() {\r\n");
      out.write("\t\t$(this).css(\"color\", \"white\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"#video\").mousedown(function() {\r\n");
      out.write("\t\tlocation.href = \"/TAMINO/newscontrol?command=videolist\";\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("\r\n");
      out.write("\t$(\".box3\").slice(0,6).show();\r\n");
      out.write("\t$(\"#load\").click(function(e) {\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t\t$(\".box3:hidden\").slice(0,6).show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif($(\".box3:hidden\").length==0){\r\n");
      out.write("\t\t\t$(\"#load\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
